#!/usr/bin/perl
use strict;
use warnings;

my %events;
my $distro = "maverick";
my $pkg_url = "http://packages.ubuntu.com/$distro";

print qq!<data date-time-format="iso8601">\n!;

while(<>) { 
  my ($package, $action, $colour);

  my @fields = split(/\s+/);
  my $date = "$fields[0] $fields[1]";

  if ($fields[2] =~ /remove|upgrade/) {
    $action  = $fields[2];
    $package = $fields[3];
    $colour  = 'red';
  }

  if ($fields[3] =~ /^installed$/) {
    $action  = $fields[3];
    $package = $fields[4];
    $colour  = 'green';
  }

  next unless defined $action;

  my $url = qq!&lt;a href="$pkg_url/$package"&gt;$distro/$package&lt;/a&gt;!;

  print qq!  <event start='$date' title='$action: $package' color='$colour'>$url</event>\n!;

}

print "</data>\n";
