#!/usr/bin/bash
set -e

git fetch
branch_name=$(git symbolic-ref --short -q HEAD)

if [ ! -z "$1" ];then
  branch_name="$1"
fi

echo "diff $branch_name origin/$branch_name"

git diff $branch_name origin/$branch_name
